# config/packages/easy_admin.yaml
easy_admin:
  design:
    assets:
      # all kinds of assets are supported and linked accordingly
      css:
        - 'https://unpkg.com/purecss@2.0.6/build/grids-responsive-min.css'
  entities:
    - App\Entity\Track
    - App\Entity\Album
    - App\Entity\Artist
    - App\Entity\Playlist