vich_uploader:
    db_driver: orm
    mappings:
        album_images:
            uri_prefix: '%app.path.album_images%'
                upload_destination: '%kernel.project_dir%/public%app.path.album_images%'
        playlist_images:
            uri_prefix: '%app.path.playlist_images%'
                upload_destination: '%kernel.project_dir%/public%app.path.playlist_images%'