version: '3'

services:
    nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - '.:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8000:80'
        depends_on:
            - php
    db:
        build:
            context: ./docker/mysql
        image: mysql:5.7
        restart: on-failure
        volumes:
            - ./docker/mysql/conf.d/config.cnf:/etc/mysql/conf.d/config.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=db_password
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
            - MYSQL_DATABASE=db_name
        ports:
            - '54325:3306'
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - '.:/usr/src/app'
        restart: on-failure
        env_file:
            - .env
        user: 1000:1000
        depends_on:
            - db